name: CI Workflow for Stellar Model

on: [push]

jobs:
  build_and_train:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        pip install mlflow pandas scikit-learn matplotlib seaborn

    - name: Run Model Training with MLflow Project
      run: |
        # PERBAIKAN: Masuk ke folder sesuai struktur terbaru Anda
        cd MLProject
        # Gunakan env-manager local agar sukses di GitHub Actions
        mlflow run . --experiment-name "Stellar_CI_Run" --env-manager local

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: trained-model-artifacts
        # Sesuaikan path ke lokasi mlruns di dalam folder MLProject
        path: MLProject/mlruns/